import Head from "next/head";
import styles from "../styles/Home.module.css";
import { AiFillGithub, AiOutlineCodepen } from "react-icons/ai";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.home__container}>
        <div className={styles.home__container__info}>
          <h3>Hi, my name is</h3>
          <h2>Stefan Traciu</h2>
          <h3>I build things that lives on the internet </h3>
          <p>
            Enthusiastic and motivated frontend developer, who enjoys turning
            problems into simple, beautiful and accessible designs. Currently,
            I&apos;m focus on gaining more experience in my field and working
            with new tools.
          </p>
          <div>
            <ul>
              <li>
                <Link href="https://github.com/trstefan">
                  <AiFillGithub />
                </Link>
              </li>
              <li>
                <Link href="https://codepen.io/trstefan">
                  <AiOutlineCodepen />
                </Link>
              </li>
            </ul>
          </div>
          <div>
            <Link href="/about">
              <button className={styles.button}> View More</button>
            </Link>

            <Link href="/projects">
              <button className={styles.button}> View Projects</button>
            </Link>
          </div>
        </div>
      </div>
    </>
  );
}

export async function getStaticProps() {
  return {
    props: { title: "Home" },
  };
}
